trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/node.zip'
    replaceExistingArchive: true
    verbose: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Parshwa-Azure'
    appType: 'webAppLinux'
    WebAppName: 'ankittaskbackend'
    deployToSlotOrASE: true
    ResourceGroupName: 'Task-Backend'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)'
    RuntimeStack: 'NODE|16-lts'
    StartupCommand: 'node index.js'